### ISSUE TITLE
Rai contact?

### ISSUE THREAD

**Issue by caspertone2003** [lithium0003/DecodeCarotDAV#3]
Hi,
I know this place is not for CarotDAV/Rei, but situation is specialç

GDrive stopped accepting new links from CarotDav some months ago, as the changed the authentication protocols.

There has not been any update to CarotDav since january 2022. Author does not answer email (used to answer) and has not issued any update to any of its sw.

Anyone has access to Rai? Could his/her code become open source if 

TIA

**Comment by lithium0003** [comment]
Hi,
CarotDAV/Rei author has a twitter account, and I told him/her that the GDrive auth is not working. He/She said the developing PC had broken(mail account in it)... need to fix it and recover data.

**Comment by caspertone2003** [comment]
@lithium0003 
Thanks very much!
I was not aware he/she had a twitter account - I have not ... so did not even thinkg about that way.
I was really worried, he/she is a very nice person and usually answered email. And Covid has been such an issue on these years... Difficult with his/her english, but nice.

And CarotDAV such a wondrful product!
Besides this, thank you for creating this DecodeCarotDAV. Otherwise we could lose our lovely encoded data if the sw would be unable to access GDrive!!

Thanks again!
