### ISSUE TITLE
Another favour please

### ISSUE THREAD

**Issue by caspertone2003** [lithium0003/DecodeCarotDAV#4]
Hi,
This is me again.

Unfortunately CarotDAV registration with google is failing again...
But I am unable to contact with Rei.

Could you please tell him/her about the situation?

This is what google delivers after trying to register:

![image](https://github.com/lithium0003/DecodeCarotDAV/assets/4682903/7be9f43c-9f42-4b8f-8fd5-bfadabc446b0)

Thanks again!

**Comment by lithium0003** [comment]
Hello,
I told to Rei this error via twitter. Please wait him/her.
Thanks.

**Comment by caspertone2003** [comment]
Hi,
could you give him/her a ping?
I saw no change to the sw, so I am unable to  use it with new google accounts ...
Thanks again!

**Comment by lithium0003** [comment]
Hello,
He/She is now contacting google for new authorizing steps, it seems to be hard step...
The google new authorizing step for drive app become very strict for a personal developer.

**Comment by lithium0003** [comment]
Hello,
I contacted him/her and he/she said that too busy now but maybe be able to follow new authorizing steps, so the app will be updated in a bit.

**Comment by caspertone2003** [comment]
Thanks again for your great help!
